name: todo_app_location
description: To-Do List App with Location-Based Features

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.0.5

  # Database lokal
  sqflite: ^2.2.8+4
  path: ^1.8.4

  # Local Storage
  shared_preferences: ^2.2.1

  # Maps & Location
  google_maps_flutter: ^2.3.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

  # Utilities
  intl: ^0.18.1

  # UI
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true